import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>LinHsu-Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pro.ico" />
      </Head>

      <h1 className="text-3xl font-bold underline">Hello world!</h1>
    </div>
  );
}
